// <auto-generated />
using System;
using FinanceHelper.Core.Domain.Models;
using FinanceHelper.Core.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceHelper.Core.Migrations
{
    [DbContext(typeof(FinanceHelperDbContext))]
    [Migration("20250616220858_ModelUpdates")]
    partial class ModelUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceHelper.Core.Domain.Models.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<FinancialAnalysis>("Analysis")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transactions_hash");

                    b.HasKey("Id");

                    b.HasIndex("TransactionHash")
                        .IsUnique();

                    b.ToTable("analysis_results");
                });

            modelBuilder.Entity("FinanceHelper.Core.Domain.Models.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
